### PR TITLE
Move /save endoint to /_/save. Even if it uses POST so there is no co…

### PR DESCRIPTION
**Pull request by pcorpet**
…nflict with the redirector, it's cleaner to have it there.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/pcorpet/url-shortener/11)

### CODE REVIEW

**Comment by florianjourda** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[public/index.html, line 24 [r1]](https://reviewable.io:443/reviews/pcorpet/url-shortener/11#-KCQ9U9G836ZFrgL8HYc:-KCQ9U9G836ZFrgL8HYd:1313203914) ([raw file](https://github.com/pcorpet/url-shortener/blob/e8d6913d2b4b29e7f7ffd10d58bd066c9eeb07fb/public/index.html#L24)):_
What about putting _ into a constant?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pcorpet/url-shortener/11#-:-KCQ9twMZxkQR6MfXASq:1417088721)_

**Comment by florianjourda** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pcorpet/url-shortener/11)_

**Comment by pcorpet** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[public/index.html, line 24 [r1]](https://reviewable.io:443/reviews/pcorpet/url-shortener/11#-KCQ9U9G836ZFrgL8HYc:-KCQqRAwhoW0ucKlI1aS:-499146009) ([raw file](https://github.com/pcorpet/url-shortener/blob/e8d6913d2b4b29e7f7ffd10d58bd066c9eeb07fb/public/index.html#L24)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pcorpet/url-shortener/11)_

**Comment by florianjourda** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[server.go, line 48 [r2]](https://reviewable.io:443/reviews/pcorpet/url-shortener/11#-KCR6qlku-BnpZHhcBYP:-KCR6qllwVHaw5QdmpKM:-1805278178) ([raw file](https://github.com/pcorpet/url-shortener/blob/73568b81d802293d1ec0a2dd942520d5b9b96e7d/server.go#L48)):_
too many things in one line

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pcorpet/url-shortener/11#-:-KCR7BkabDCAL6dT4SOG:1417088721)_

**Comment by pcorpet** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[server.go, line 48 [r2]](https://reviewable.io:443/reviews/pcorpet/url-shortener/11#-KCR6qlku-BnpZHhcBYP:-KCRGpIfCOOAujm4TbZK:-499146009) ([raw file](https://github.com/pcorpet/url-shortener/blob/53209217e068b1e014ad05815b08b83426023322/server.go#L48)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pcorpet/url-shortener/11)_

**Comment by florianjourda** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pcorpet/url-shortener/11#-:-KCRID8oUe96L3QJkNSS:1417088721)_

**Pull request merged**
